import { useContext } from 'react'
import { AuthContext } from '../App'
import jsPDF from 'jspdf'

function PdfDownload({ result }) {
  const { user } = useContext(AuthContext)

  const downloadPDF = () => {
    const doc = new jsPDF()

    // Background header
    doc.setFillColor(34, 197, 94)
    doc.rect(0, 0, 210, 40, 'F')

    // Title
    doc.setFontSize(26)
    doc.setTextColor(255, 255, 255)
    doc.setFont("helvetica", "bold")
    doc.text('EcoTrack AI Report', 105, 25, { align: 'center' })

    // User Info
    doc.setFontSize(12)
    doc.setTextColor(50, 50, 50)
    doc.setFont("helvetica", "normal")
    const safeName = result.name ? result.name.replace(/[^\x00-\x7F]/g, "") : "Eco User"
    doc.text(`Name: ${safeName}`, 20, 60)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 140, 60)

    // Divider
    doc.setDrawColor(200, 200, 200)
    doc.line(20, 65, 190, 65)

    // Emission Summary
    doc.setFontSize(16)
    doc.setTextColor(34, 197, 94)
    doc.setFont("helvetica", "bold")
    doc.text('Emission Summary', 20, 80)

    // Table Headers
    doc.setFillColor(240, 240, 240)
    doc.rect(20, 85, 170, 10, 'F')
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text('Category', 25, 92)
    doc.text('Emission (kg CO2)', 140, 92)

    // Table Content
    doc.setFont("helvetica", "normal")
    doc.text('Transport', 25, 102)
    doc.text(`${result.transport_emission}`, 140, 102)

    doc.text('Electricity', 25, 112)
    doc.text(`${result.electricity_emission}`, 140, 112)

    doc.text('Fuel', 25, 122)
    doc.text(`${result.fuel_emission}`, 140, 122)

    doc.text('Food', 25, 132)
    doc.text(`${result.food_emission}`, 140, 132)

    // Divider
    doc.line(20, 138, 190, 138)

    // Totals
    doc.setFont("helvetica", "bold")
    doc.setFontSize(14)
    doc.text('Total Emission:', 25, 148)
    doc.setTextColor(239, 68, 68) // Red
    doc.text(`${result.total_emission} kg CO2`, 140, 148)

    // Grade and Badge
    doc.setTextColor(34, 197, 94)
    doc.text('Eco Grade:', 25, 158)
    doc.setTextColor(0, 0, 0)
    doc.text(`${result.grade} (${result.grade_label})`, 140, 158)

    // Insights Box
    doc.setDrawColor(34, 197, 94)
    doc.setFillColor(245, 255, 245)
    doc.roundedRect(20, 170, 170, 40, 3, 3, 'FD')
    
    doc.setFontSize(14)
    doc.setTextColor(34, 197, 94)
    doc.text('AI Recommendation', 25, 180)

    doc.setFontSize(11)
    doc.setTextColor(50, 50, 50)
    doc.setFont("helvetica", "normal")
    
    const cleanTip = result.tip ? result.tip.replace(/[^\x00-\x7F]/g, "").trim() : ""
    const cleanSuggestion = result.suggestion ? result.suggestion.replace(/[^\x00-\x7F]/g, "").trim() : ""
    
    doc.text(`Top Source: ${result.highest_source}`, 25, 190)
    doc.text(`Action: ${cleanTip}`, 25, 198)
    
    const lines = doc.splitTextToSize(`Suggestion: ${cleanSuggestion}`, 160)
    doc.text(lines, 25, 206)

    // Footer
    doc.setFontSize(10)
    doc.setTextColor(150, 150, 150)
    doc.text('Generated by EcoTrack AI • Save the planet, one step at a time.', 105, 280, { align: 'center' })

    doc.save(`EcoTrack_Report_${safeName.replace(/\s+/g, '_')}.pdf`)
  }

  return (
    <button onClick={downloadPDF} style={{ background: '#3b82f6', marginTop: '10px' }}>
      📄 Download PDF Report
    </button>
  )
}

export default PdfDownload
